export const european_countries = [
  "Albania 🇦🇱",
  "Andorra 🇦🇩",
  "Austria 🇦🇹",
  "Belarus 🇧🇾",
  "Belgium 🇧🇪",
  "Bosnia and Herzegovina 🇧🇦",
  "Bulgaria 🇧🇬",
  "Croatia 🇭🇷",
  "Cyprus 🇨🇾",
  "Czech Republic 🇨🇿",
  "Denmark 🇩🇰",
  "Estonia 🇪🇪",
  "Finland 🇫🇮",
  "France 🇫🇷",
  "Germany 🇩🇪",
  "Greece 🇬🇷",
  "Hungary 🇭🇺",
  "Iceland 🇮🇸",
  "Ireland 🇮🇪",
  "Italy 🇮🇹",
  "Latvia 🇱🇻",
  "Liechtenstein 🇱🇮",
  "Lithuania 🇱🇹",
  "Luxembourg 🇱🇺",
  "Malta 🇲🇹",
  "Monaco 🇲🇨",
  "Montenegro 🇲🇪",
  "Netherlands 🇳🇱",
  "North Macedonia 🇲🇰",
  "Norway 🇳🇴",
  "Poland 🇵🇱",
  "Portugal 🇵🇹",
  "Romania 🇷🇴",
  "San Marino 🇸🇲",
  "Serbia 🇷🇸",
  "Slovakia 🇸🇰",
  "Slovenia 🇸🇮",
  "Spain 🇪🇸",
  "Sweden 🇸🇪",
  "Switzerland 🇨🇭",
  "Turkey 🇹🇷",
  "Ukraine 🇺🇦",
  "United Kingdom 🇬🇧",
  "Vatican City 🇻🇦",
];
